language: java
sudo: false # faster builds

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8

before_install:
  - pip install --user codecov

script: mvn test -B -N

after_success:
  - codecov
